// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBz1aiLYamAdV26JErP9jVGn6EtMTko4I',
    appId: '1:715184160705:web:32cde281448d0c37a0f940',
    messagingSenderId: '715184160705',
    projectId: 'vize-030120080',
    authDomain: 'vize-030120080.firebaseapp.com',
    storageBucket: 'vize-030120080.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBE7mBMrqKJrrgXqbliQHt_mS_I5z_xO3w',
    appId: '1:715184160705:android:9fee9a509ef96453a0f940',
    messagingSenderId: '715184160705',
    projectId: 'vize-030120080',
    storageBucket: 'vize-030120080.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDksSBLosJJ3BVrEXoiYGbvBAPytGio5U4',
    appId: '1:715184160705:ios:27e6f57e9eb948d0a0f940',
    messagingSenderId: '715184160705',
    projectId: 'vize-030120080',
    storageBucket: 'vize-030120080.appspot.com',
    iosClientId: '715184160705-jnj0o3qo0pmh3nn2sosnrq5a3akffgn2.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDksSBLosJJ3BVrEXoiYGbvBAPytGio5U4',
    appId: '1:715184160705:ios:27e6f57e9eb948d0a0f940',
    messagingSenderId: '715184160705',
    projectId: 'vize-030120080',
    storageBucket: 'vize-030120080.appspot.com',
    iosClientId: '715184160705-jnj0o3qo0pmh3nn2sosnrq5a3akffgn2.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );
}
